fix: Fix test data generator
cloudquery/plugin-sdk pull request #1081
Opened 2023-07-06 14:10 UTC by hermanschaaf

The counter wasn't properly incrementing because we weren't using a pointer in `getExampleJSON`

2023-07-06 14:13 UTC, candiduslynx approved these changes

2023-07-06 14:19 UTC, hermanschaaf commented
Actually I think it was fine, so this fix does nothing, but probably still a good idea to use pointers consistently. I got confused because `testInsertBasic` inserts id 1 twice in a row, but it's not using the generator.

2023-07-06 14:22 UTC, hermanschaaf commented
I pushed another commit to update the basic insert test to use different values in the two rows.

2023-07-07 08:38 UTC, candiduslynx requested changes

2023-07-07 08:43 UTC, hermanschaaf commented on plugin/testing_write_insert.go
> +		Record: record2,
These records don't actually contain any nulls though

2023-07-07 09:56 UTC, candiduslynx approved these changes

2023-07-07 12:02 UTC, disq approved these changes

2023-08-23 10:09 UTC, closed without merging