Add column meta struct
cloudquery/plugin-sdk pull request #13
Opened 2022-08-24 14:56 UTC by hermanschaaf

I'm not sure whether this is necessarily the cleanest way to handle it, but having the original name of a field allows us to do the following inside the generate code:

```
	for u, c := range r.Table.Columns {
		if c.Meta.OriginalName != strcase.ToCamel(c.Name) {
			r.Table.Columns[u].Resolver = fmt.Sprintf(`schema.PathResolver(%q)`, c.Meta.OriginalName)
		}
	}
```

This then handles cases like `ID`, `DocURL`, etc automatically.

2022-08-24 16:13 UTC, erezrokah approved these changes

2022-08-24 17:41 UTC, yevgenypats requested changes
One nit

2022-08-24 17:41 UTC, yevgenypats commented on codegen/golang.go
> +				OriginalName: field.Name,
Nit: Let's just put it as a field `OriginalName` ? this will eliminate another meta  `meta` definition ?

2022-08-25 06:57 UTC, hermanschaaf commented
Closing in favor of https://github.com/cloudquery/plugin-sdk/pull/14

2022-08-25 06:57 UTC, closed without merging