fix: Fix docs for deeply nested tables
cloudquery/plugin-sdk pull request #434
Opened 2022-11-24 15:10 UTC by hermanschaaf

Closes https://github.com/cloudquery/plugin-sdk/issues/428

2022-11-24 15:45 UTC, candiduslynx requested changes
spaces

2022-11-24 16:15 UTC, candiduslynx requested changes

2022-11-24 16:15 UTC, candiduslynx commented on plugins/templates/table.md.go.tpl
> +{{if $.Parent }}
what does it do?

2022-11-24 16:15 UTC, candiduslynx commented on plugins/templates/table.md.go.tpl
> +{{ if $.Relations -}}
what does it do?

2022-11-24 16:15 UTC, candiduslynx commented on plugins/.snapshots/TestGenerateSourcePluginDocs-Markdown-test_table.md
> +
extra empty line seems extra, maybe move it under parent presence check?

2022-11-24 16:26 UTC, candiduslynx approved these changes

2022-11-25 10:14 UTC, disq approved these changes

2022-11-25 11:04 UTC, candiduslynx approved these changes

2022-11-25 11:05 UTC, yevgenypats approved these changes

2022-11-25 11:10 UTC, merged