chore(ci): Bring back benchmark comment
cloudquery/plugin-sdk pull request #441
Opened 2022-11-28 17:08 UTC by erezrokah

#### Summary

Brings back the benchmark comment based on https://github.com/cloudquery/plugin-sdk/pull/437#issuecomment-1329194054

This should only start working post merge (I hope) as the triggering workflow file needs to be on the `main` branch

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2022-11-28 17:16 UTC, hermanschaaf requested changes
Nice, thanks for updating this! Just the one comment so we get text comments rather than the quite lengthy graph outputs

2022-11-28 17:17 UTC, hermanschaaf commented on .github/workflows/unittest-post.yml
> +          pr_number: ${{ steps.pr_number.outputs.pr_number }}
Does it also need a token, or will that default to GITHUB_TOKEN?

2022-11-29 09:01 UTC, erezrokah commented on .github/workflows/unittest-post.yml
> +          pr_number: ${{ steps.pr_number.outputs.pr_number }}
It defaults to the `GITHUB_TOKEN` which should have comment write permissions when running from `workflow_run` context

2022-11-29 09:03 UTC, hermanschaaf approved these changes

2022-11-29 09:05 UTC, merged