feat: Add Support for net.IP in Faker
cloudquery/plugin-sdk pull request #445
Opened 2022-11-30 12:43 UTC by bbernays

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2022-11-30 13:17 UTC, erezrokah requested changes
Thanks @bbernays, added 2 comments.
Can you also link to which mock test faking an IP is required?

2022-11-30 13:20 UTC, bbernays commented on faker/faker.go
> +		case "net.IP":
This is how `time.Time` is handled on line 46... Happy to change, but was trying to keep consistency within the function

2022-11-30 13:20 UTC, bbernays commented on faker/faker_test.go
> +	assert.NotEmpty(t, a.F)
Yeah will do that. Haven't finished the tests yet

2022-11-30 14:17 UTC, erezrokah commented on faker/faker.go
> +		case "net.IP":
Got, so we can keep it like this and refactor in a future PR

2022-11-30 14:19 UTC, erezrokah commented on faker/faker_test.go
> +func TestFakerWithComplexCustomType(t *testing.T) {
```suggestion
func TestFakerCanFakeNet.IP(t *testing.T) {
```

[non blocking] Maybe a name that describes what we're testing in a more specific way

2022-12-02 10:22 UTC, yevgenypats requested changes
doesn't that produce a valid IP only for for slice? what about `map`, `ptr` or just field in struct ?

2022-12-02 10:23 UTC, yevgenypats commented
Or maybe I miss something as seems the tests does pass? didn't touch that code for a while....

2022-12-02 18:43 UTC, bbernays commented
> doesn't that produce a valid IP only for for slice? what about map, ptr or just field in struct ? 

`net.IP` is defined as as a `type IP []byte` slice so we only have to handle that one special type of `slice`

2022-12-05 15:39 UTC, merged