fix(destinations): Propagate write errors
cloudquery/plugin-sdk pull request #461
Opened 2022-12-05 15:07 UTC by erezrokah

#### Summary

Related to https://github.com/cloudquery/cloudquery/issues/5152 and https://github.com/cloudquery/plugin-sdk/pull/460

The error returned from the error group `Wait()` function is the [error reported by the Go routine](https://github.com/cloudquery/plugin-sdk/blob/ab7ca972e0b187a7dfb66132a03f07479cd29bb7/internal/servers/destinations.go#L84), not the error of the `Wait()` function

> This is only a patch. I think we should separate application level errors (e.g. write) from protocol/communication level errors. I'll open a separate issue for that.

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

2022-12-06 09:00 UTC, hermanschaaf requested changes

2022-12-06 09:07 UTC, erezrokah commented on internal/servers/destinations.go
> +				return fmt.Errorf("plugin write failed: %w", err)
Yeah, I'm not sure. I actually think we should return a list of errors, but that's a bigger change.
I think the `Write` error is the first one that occurred so it makes more sense to return it.
I'll add a log for the unmarshal error

2022-12-11 16:25 UTC, erezrokah commented on internal/servers/destinations.go
> +				return fmt.Errorf("plugin write failed: %w", err)
https://github.com/cloudquery/plugin-sdk/pull/487 should allow us to report both

2022-12-27 15:29 UTC, erezrokah commented
Closed by https://github.com/cloudquery/plugin-sdk/pull/529

2022-12-27 15:29 UTC, closed without merging