fix: Close channel in separate defer()
cloudquery/plugin-sdk pull request #471
Opened 2022-12-07 16:09 UTC by disq

Otherwise if the `close` panics it won't be caught.

2022-12-07 16:28 UTC, erezrokah approved these changes

2022-12-07 16:48 UTC, yevgenypats commented
What effect this PR has? also seem tests are failing?

2022-12-07 17:27 UTC, disq commented
> What effect this PR has? also seem tests are failing?

Made it betterer with [`0636bef` (#471)](https://github.com/cloudquery/plugin-sdk/pull/471/commits/0636bef47e982183eceb43947ebabcc1ba1a0273)

Not necessarily a bugfix but makes it easier to read

2022-12-08 08:18 UTC, yevgenypats requested changes
Let's avoid for now pushing code that has no effect to the SDK given how hard it is to test things at scale and this code works (also I think I had it this way but in a review I got it was requested to move this to this place so it will just continue to move around) .

2022-12-08 08:45 UTC, hermanschaaf commented on plugins/source_scheduler_dfs.go
> +				close(res) // assuming the panic is from the resolver, don't leave the channel open
I guess the panic could have also been from closing the channel, in which case we'd be causing another panic here 😅

2022-12-08 09:40 UTC, closed without merging