test: Add null-in-test-field test
cloudquery/plugin-sdk pull request #532
Opened 2022-12-26 09:51 UTC by shimonp21

Closes https://github.com/cloudquery/cloudquery/issues/5255 after we upgrade the sdk's in the dest-plugins

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2022-12-26 09:55 UTC, erezrokah approved these changes
Looks good but is there anything else we should string? Not sure 🙃

2022-12-27 11:09 UTC, disq commented on schema/text.go
> +// Used only in tests - we allow one of the strings to be missing null byttes (since some destinations like)
```suggestion
// Used only in tests - we allow one of the strings to be missing null bytes (since some destinations like)
```

2023-01-11 16:46 UTC, yevgenypats requested changes
Maybe worth live discussion as don't understand the whole context but

 `return dst.Status == s.Status && strings.ReplaceAll(dst.Str, "\x00", "") == strings.ReplaceAll(s.Str, "\x00", "")` seems a line that can cause issues in the future.

2023-02-07 14:18 UTC, yevgenypats approved these changes

2023-02-08 08:50 UTC, merged