feat(destinations): Add `migrate_mode`
cloudquery/plugin-sdk pull request #604
Opened 2023-01-12 15:23 UTC by erezrokah

#### Summary

Related to https://github.com/cloudquery/cloudquery/issues/6600

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

2023-01-12 15:49 UTC, erezrokah commented on specs/destination.go
> +	MigrateMode    MigrateMode `json:"migrate_mode,omitempty"`
This can also be a boolean, just found it easier to communicate the purpose using strings

2023-01-12 18:47 UTC, hermanschaaf approved these changes
This LGTM; are we also planning on supporting a `--migrate forced` (or similar) flag for the CLI? Might make it a bit easier for users doing things interactively

2023-01-12 18:50 UTC, hermanschaaf commented
We're also not using the setting anywhere yet - is that because it needs to be implemented in each destination? I think we'll need to pass the mode in to the `Migrate` call so that destinations can act on it?

2023-01-13 10:17 UTC, disq approved these changes

2023-01-15 12:08 UTC, erezrokah commented
> a `--migrate forced` (or similar) flag for the CLI? Might make it a bit easier for users doing things interactively

So a CLI will we have to "take" for all specs, where a spec config only "takes" on the specific spec. We can consider adding it but I don't think we can similar flags (that override spec configuration(s))

2023-01-15 15:38 UTC, yevgenypats requested changes
Looks good. One nit:

Can we move migrate enum code to `migrate.go` as looks like our enums are growing and maybe also add a small sanity test for marshal/unmarsahl.

2023-01-15 16:23 UTC, erezrokah commented
> Can we move migrate enum code to `migrate.go` as looks like our enums are growing and maybe also add a small sanity test for marshal/unmarsahl.

Sure, good point. Let me know if https://github.com/cloudquery/plugin-sdk/pull/604/commits/1ff6062f3821a20e6a7e67f1aee6e026288b2cbb is what you had in mind

2023-01-15 17:15 UTC, yevgenypats approved these changes

2023-01-15 17:53 UTC, merged