chore(test): Add overwrite + migrate destination plugin test
cloudquery/plugin-sdk pull request #618
Opened 2023-01-19 15:56 UTC by candiduslynx

2023-01-23 10:06 UTC, hermanschaaf requested changes
It seems like the test runs the code in overwrite mode, but doesn't actually do any overwrite-specific assertions, because all the items being written have unique PKs. Shouldn't we test / expect some difference between append and overwrite modes?

2023-01-23 10:09 UTC, candiduslynx commented
> It seems like the test runs the code in overwrite mode, but doesn't actually do any overwrite-specific assertions, because all the items being written have unique PKs. Shouldn't we test / expect some difference between append and overwrite modes?

We want to test that overwrite works if the column order changed. The actual overwrite with check regarding overwritten data is done in a separate test.

2023-01-23 10:38 UTC, hermanschaaf approved these changes

2023-01-24 12:43 UTC, yevgenypats approved these changes

2023-01-24 12:50 UTC, merged