fix: Remove sentry sending from destinations
cloudquery/plugin-sdk pull request #707
Opened 2023-02-22 21:57 UTC by yevgenypats

Right now the logic is not quite correct as if there are duplicate pks in the destination we should just filter but no reason to send to sentry. multiple sources can sync the same resources and it should be all good. We also check duplicates on the source level (and I think send to sentry) so no need to do it twice.

2023-02-22 23:38 UTC, candiduslynx commented
I remember that we created this report when we didn't check duplicates on the source side.
Could you link a corresponding PR that implemented this change?

2023-02-23 07:33 UTC, yevgenypats commented
> I remember that we created this report when we didn't check duplicates on the source side. Could you link a corresponding PR that implemented this change?

If we don't have then we should only send it on the source side. either way this have to go.

2023-02-23 08:44 UTC, hermanschaaf commented
Agree it would be better on the source side, but I'm not sure how this can be implemented there? The only way I can think of would be to keep a map of seen PKs per table in the `Sync` server function, but this would add quite a lot of overhead. If it's already implemented, I'd like to see where this is done :)

2023-02-23 09:40 UTC, candiduslynx requested changes
We don't send from the source side currently.
I don't think we should disable this on the destination side until source reporting is implemented.

2023-04-04 10:48 UTC, candiduslynx commented
Closing in favor of #760

2023-04-04 10:48 UTC, closed without merging