fix: Custom handling for Arrow type strings in docs
cloudquery/plugin-sdk pull request #896
Opened 2023-05-22 09:15 UTC by hermanschaaf

This adds custom handling for Arrow types during docs generation. Previously we relied on the `.String()` method, but for extensions this doesn't print anything meaningful (e.g. JSON was printed as `fix_size_binary`), and in a few cases it was a bit confusing (e.g. using `utf8` instead of `string`). It's better if we control the format, and perhaps later the formatting function can become a public function of the `types` package so that it can be applied consistently.

2023-05-22 10:47 UTC, disq approved these changes

2023-05-22 10:54 UTC, candiduslynx requested changes
I do feel that the Arrow Types are OK in terms of defining what is actually going on.
So, maybe just do an upstream PR to remove the timezone if the tz is `UTC`? (it's the default, so no need to actually print it out if not explicitly asked for)

Additionally, there's an issue with unhandled nested type nullability in this proposal.

2023-05-22 10:54 UTC, candiduslynx commented on plugins/source/docs.go
> +			return "large_list<" + formatType(v.(*arrow.LargeListType).Elem()) + ">"
you lose the info about elem nullability here (and it might be vital to know if the elem can be nullable or not (think CH destination))

2023-05-22 11:41 UTC, hermanschaaf commented
@candiduslynx Updated. The main thing I wanted to fix was that JSON was being printed as `extension_type<fixed_byte_list>` or something along those lines; turns out this was part of its `String()` definition, so I could fix it there. I don't love the Arrow `String()` implementation, as it seems inconsistent between nested types and `utf8` is not as good a name as `string`, but I think we can live with these things for now.

2023-05-22 11:50 UTC, candiduslynx requested changes

2023-05-22 11:50 UTC, candiduslynx commented on plugins/source/docs.go
> +				Type:             formatType(col.Type),
```suggestion
				Type:             col.Type.String(),
```

2023-05-22 11:51 UTC, candiduslynx commented on plugins/source/docs.go
> +				Type:             formatType(col.Type),
and remove the `formatType` func

2023-05-22 12:24 UTC, candiduslynx approved these changes

2023-05-24 07:42 UTC, yevgenypats approved these changes

2023-05-24 07:45 UTC, merged